GlobalConfig:
  lang: 'zh'
ModelConfig:
  #  dataset: 'all'
  dataset: 'part'
  split: 0.2
  ano: 0
  EPOCH: 30
  BATCH_SIZE: 64
  LEARNING_RATE: 0.001
  TIME_STEPS: 1
  FEATURE_SELECT: 0
  ATTENTION: 'global'
  SHOW: 1
  READ: 0
  DAYS: 360

AEConfig:
  SHOW_ANOMALY: show
  REMAKE_EPOCH: 100
  TIME_STEPS: 1
  BATCH_SIZE: 128
  SHOW: 0

