GlobalConfig:
  lang: 'zh'
ModelConfig:
  #  dataset: 'all'
  dataset: 'part'
  split: 0.2
  ano: 0
  EPOCH: 300
  BATCH_SIZE: 64
  LEARNING_RATE: 0.001
  TIME_STEPS: 1
  FEATURE_SELECT: 0
  ATTENTION: 'global'
  SHOW: 1
  READ: 0
  DAYS: 360
  data_path: 'data_1710770284_ano.csv'

AEConfig:
  SHOW_ANOMALY: show
  REMAKE_EPOCH: 100
  TIME_STEPS: 1
  BATCH_SIZE: 128
  SHOW: 0

