GlobalConfig:
  lang: 'zh'
ModelConfig:
  #  dataset: 'all'
  dataset: 'part'
  split: 0.2
  ano: 0
  EPOCH: 100
  BATCH_SIZE: 128
  LEARNING_RATE: 0.001
  TIME_STEPS: 6
  FEATURE_SELECT: 0
  ATTENTION: 'global'
  SHOW: 0
  READ: 0
  DAYS: 60
  data_path: 'data_1711265228_ano.csv'

AEConfig:
  SHOW_ANOMALY: show
  REMAKE_EPOCH: 100
  TIME_STEPS: 1
  BATCH_SIZE: 128
  SHOW: 1

